listening-port=3478
# tls-listening-port=5349   ← закомментируйте, TLS всё равно не настроен

use-auth-secret
static-auth-secret=922cb06fa31c9ccb4c7978e3d7fde39078e099fa880edc87a68748db57b4c84c
realm=p2p-chat

listening-ip=0.0.0.0
relay-ip=0.0.0.0
no-dynamic-ip-list

min-port=49152
max-port=49252

no-multicast-peers
denied-peer-ip=0.0.0.0-0.255.255.255
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=127.0.0.0-127.255.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=172.16.0.0-172.16.255.255
# 172.17.0.0/16 пропускаем — это Docker-хост
denied-peer-ip=172.18.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=::1
denied-peer-ip=::ffff:0.0.0.0-::ffff:255.255.255.255
denied-peer-ip=fc00::-fdff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
denied-peer-ip=fe80::-febf:ffff:ffff:ffff:ffff:ffff:ffff:ffff

no-rfc5780
no-software-attribute

user-quota=100
total-quota=10000
max-allocate-lifetime=3600
unauthorized-ratelimit
unauthorized-ratelimit-rps=10

log-file=stdout
verbose

fingerprint
stale-nonce=600